### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by shinnn**
[through2](https://github.com/rvagg/through2) is now v2.0.0 that uses Streams3. (through2 v0.4.x uses Streams2.)

### CODE REVIEW

**Comment by binocarlos** [comment]
thanks!

**Comment by binocarlos** [comment]
just pushed `0.0.4` to npm

**Comment by shinnn** [comment]
> pushed 0.0.4 to npm

Please bump version in the `package.json` in this repository, too. That's still `0.0.3`. https://github.com/binocarlos/from2-array/blob/d25a13f7c60f5f640aa813b306d9ee76d8a5964a/package.json#L3

**Comment by binocarlos** [comment]
ummm that was dumb of me sorry pushed now :-)

**Pull request merged**
